[build]
 
  publish = "." # 배포할 파일들이 있는 경로

[[redirects]]
  from = "/save_store/*"
  to = "https://clovagood.netlify.app/save_store/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_restaurant/*"
  to = "https://clovagood.netlify.app/place_restaurant/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_drink_alcohol/*"
  to = "https://clovagood.netlify.app/place_drink_alcohol/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_drink_caffeine/*"
  to = "https://clovagood.netlify.app/place_drink_caffeine/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_play_game/*"
  to = "https://clovagood.netlify.app/place_play_game/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_sing/*"
  to = "https://clovagood.netlify.app/place_sing/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_exercise/*"
  to = "https://clovagood.netlify.app/place_exercise/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_convenience/*"
  to = "https://clovagood.netlify.app/place_convenience/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_book/*"
  to = "https://clovagood.netlify.app/place_book/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/place_laundry/*"
  to = "https://clovagood.netlify.app/place_laundry/:splat"
  status = 301
  force = true
